branch-defaults:
  master:
    environment: zulsarhan
global:
  application_name: MyPortfolio
  default_ec2_keyname: zulsarhan
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
